/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/cloud_test.glb -t 
Author: Andrey Martyanov (https://sketchfab.com/3dartel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cloud-test-6d1fff581b3a424d88ee2125f909f3f3
Title: Cloud Test
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

interface GLTFAction extends THREE.AnimationAction {
  action: THREE.AnimationAction;
}

type GLTFResult = GLTF & {
  nodes: {
    ['Plane001_08_-_Default_0']: THREE.Mesh
  }
  materials: {
    ['08_-_Default']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Cloud(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cloud_test.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Plane001_08_-_Default_0'].geometry} material={materials['08_-_Default']} position={[-0.787, 0, -5.259]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cloud_test.glb')
