/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/fountain_water_simulation.glb -t 
Author: UJJWAL CHAUHAN (https://sketchfab.com/Ujjwal-Chauhan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fountain-water-simulation-d6c0f03a8287427692078398cfda4ff1
Title: fountain water simulation
*/

import * as THREE from "three";
import React, { JSX, useEffect } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type ActionName = "Object_0";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    fShape: THREE.Mesh;
    h_1Shape: THREE.Mesh;
    f_1Shape: THREE.Mesh;
    f_3Shape: THREE.Mesh;
    f_2Shape: THREE.Mesh;
    hShape: THREE.Mesh;
  };
  materials: {
    fShape: THREE.MeshPhysicalMaterial;
    h_1Shape: THREE.MeshStandardMaterial;
    f_1Shape: THREE.MeshPhysicalMaterial;
    f_3Shape: THREE.MeshPhysicalMaterial;
    f_2Shape: THREE.MeshPhysicalMaterial;
    hShape: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Fountain({ isHovered, props }: { isHovered: string; props: JSX.IntrinsicElements["group"] }) {
  const group = React.useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/fountain_water_simulation.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions["Object_0"] && isHovered === "Fountain") {
      actions["Object_0"].play();
    } else {
      actions["Object_0"]!.stop();
    }
  }, [actions, isHovered]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="be8a82214d264a0484d09f93976b8efbabccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="Object_4" position={[0, 501.709, 5.931]}>
                  <group name="MorphMainGroup">
                    <mesh
                      name="fShape"
                      geometry={nodes.fShape.geometry}
                      material={materials.fShape}
                      morphTargetDictionary={nodes.fShape.morphTargetDictionary}
                      morphTargetInfluences={nodes.fShape.morphTargetInfluences}
                    />
                  </group>
                </group>
                <group name="Object_7" position={[0, 117.856, -6]}>
                  <group name="MorphMainGroup_1">
                    <mesh
                      name="h_1Shape"
                      geometry={nodes.h_1Shape.geometry}
                      material={materials.h_1Shape}
                      morphTargetDictionary={
                        nodes.h_1Shape.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.h_1Shape.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group name="Object_10" position={[0, 71.515, 0]}>
                  <group name="MorphMainGroup_2">
                    <mesh
                      name="f_1Shape"
                      geometry={nodes.f_1Shape.geometry}
                      material={materials.f_1Shape}
                      morphTargetDictionary={
                        nodes.f_1Shape.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.f_1Shape.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group name="Object_13" position={[0, 330.9, 0]}>
                  <group name="MorphMainGroup_3">
                    <mesh
                      name="f_3Shape"
                      geometry={nodes.f_3Shape.geometry}
                      material={materials.f_3Shape}
                      morphTargetDictionary={
                        nodes.f_3Shape.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.f_3Shape.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group name="Object_16" position={[0, 449.14, 0]}>
                  <group name="MorphMainGroup_4">
                    <mesh
                      name="f_2Shape"
                      geometry={nodes.f_2Shape.geometry}
                      material={materials.f_2Shape}
                      morphTargetDictionary={
                        nodes.f_2Shape.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.f_2Shape.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group name="Object_19">
                  <group name="MorphMainGroup_5">
                    <mesh
                      name="hShape"
                      geometry={nodes.hShape.geometry}
                      material={materials.hShape}
                      morphTargetDictionary={nodes.hShape.morphTargetDictionary}
                      morphTargetInfluences={nodes.hShape.morphTargetInfluences}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/fountain_water_simulation.glb");
