/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/indian_office_woman.glb -t 
Author: Pixel_Monster (https://sketchfab.com/ar.jethin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/indian-office-woman-e6c60cafd33c4d54b0b840c4146ed244
Title: Indian Office Woman
*/

import * as THREE from "three";
import React, { JSX, useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useAnimations, useGLTF } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "mixamo.com";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh;
    Object_8: THREE.SkinnedMesh;
    Object_9: THREE.SkinnedMesh;
    Object_10: THREE.SkinnedMesh;
    Object_11: THREE.SkinnedMesh;
    Object_12: THREE.SkinnedMesh;
    Object_13: THREE.SkinnedMesh;
    Object_14: THREE.SkinnedMesh;
    Object_15: THREE.SkinnedMesh;
    Object_16: THREE.SkinnedMesh;
    Object_17: THREE.SkinnedMesh;
    Object_18: THREE.SkinnedMesh;
    _rootJoint: THREE.Bone;
  };
  materials: {
    AvatarBody: THREE.MeshStandardMaterial;
    AvatarEyelashes: THREE.MeshStandardMaterial;
    AvatarHead: THREE.MeshStandardMaterial;
    AvatarLeftCornea: THREE.MeshStandardMaterial;
    AvatarLeftEyeball: THREE.MeshStandardMaterial;
    AvatarRightCornea: THREE.MeshStandardMaterial;
    AvatarRightEyeball: THREE.MeshStandardMaterial;
    AvatarTeethLower: THREE.MeshStandardMaterial;
    AvatarTeethUpper: THREE.MeshStandardMaterial;
    glasses: THREE.MeshStandardMaterial;
    haircut: THREE.MeshStandardMaterial;
    outfit: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};
export function WomanOffice({
  isHovered,
  props,
}: {
  isHovered: string;
  props: JSX.IntrinsicElements["group"];
}) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/indian_office_woman.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions["mixamo.com"] && isHovered === "Woman") {
      actions["mixamo.com"].play();
    } else {
      actions["mixamo.com"]!.stop();
    }
  }, [actions, isHovered]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.086}
        >
          <group
            name="7ab0120971d74f4ba654fc5c904dbf76fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="AvatarRoot">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="AvatarBody" />
                    <group name="AvatarEyelashes" />
                    <group name="AvatarHead" />
                    <group name="AvatarLeftCornea" />
                    <group name="AvatarLeftEyeball" />
                    <group name="AvatarRightCornea" />
                    <group name="AvatarRightEyeball" />
                    <group name="AvatarTeethLower" />
                    <group name="AvatarTeethUpper" />
                    <group name="glasses" />
                    <group name="haircut" />
                    <group name="outfit" />
                    <skinnedMesh
                      name="Object_7"
                      geometry={nodes.Object_7.geometry}
                      material={materials.AvatarBody}
                      skeleton={nodes.Object_7.skeleton}
                    />
                    <skinnedMesh
                      name="Object_8"
                      geometry={nodes.Object_8.geometry}
                      material={materials.AvatarEyelashes}
                      skeleton={nodes.Object_8.skeleton}
                    />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.AvatarHead}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials.AvatarLeftCornea}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <skinnedMesh
                      name="Object_11"
                      geometry={nodes.Object_11.geometry}
                      material={materials.AvatarLeftEyeball}
                      skeleton={nodes.Object_11.skeleton}
                    />
                    <skinnedMesh
                      name="Object_12"
                      geometry={nodes.Object_12.geometry}
                      material={materials.AvatarRightCornea}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <skinnedMesh
                      name="Object_13"
                      geometry={nodes.Object_13.geometry}
                      material={materials.AvatarRightEyeball}
                      skeleton={nodes.Object_13.skeleton}
                    />
                    <skinnedMesh
                      name="Object_14"
                      geometry={nodes.Object_14.geometry}
                      material={materials.AvatarTeethLower}
                      skeleton={nodes.Object_14.skeleton}
                    />
                    <skinnedMesh
                      name="Object_15"
                      geometry={nodes.Object_15.geometry}
                      material={materials.AvatarTeethUpper}
                      skeleton={nodes.Object_15.skeleton}
                    />
                    <skinnedMesh
                      name="Object_16"
                      geometry={nodes.Object_16.geometry}
                      material={materials.glasses}
                      skeleton={nodes.Object_16.skeleton}
                    />
                    <skinnedMesh
                      name="Object_17"
                      geometry={nodes.Object_17.geometry}
                      material={materials.haircut}
                      skeleton={nodes.Object_17.skeleton}
                    />
                    <skinnedMesh
                      name="Object_18"
                      geometry={nodes.Object_18.geometry}
                      material={materials.outfit}
                      skeleton={nodes.Object_18.skeleton}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/indian_office_woman.glb");
